#! /bin/bash

base=$(dirname $0)

dest=lib/setupfiles

case $1 in
    barbara*)
        host=barbara.njus.no
        ;;
    gorgon*)
        host=gorgon.hmg9.vgnett.no
        ;;
    *) echo "Unknown destination" >&2
       ;;
esac

rsync --exclude=.git -av $base/../ $host:$dest/ &&
    ssh $host $dest/support/install
