#! /bin/bash

# For available versions, see https://www.mozilla.org/en-US/firefox/organizations/all/?q=english

case $1 in
    [0-9]*) version=52.${1} ;;
    *) echo "Usage: get-firefox MINOR - fetches 52.MINOR" >&2; exit 64 ;;
esac

if [ ! -r /tmp/firefox-${version}esr.tar.bz ]
then
	wget -O /tmp/firefox-${version}esr.tar.bz "https://download.mozilla.org/?product=firefox-${version}esr-SSL&os=linux64&lang=en-US"
fi
ls -l /tmp/firefox-${version}esr.tar.bz
read -p "Unpack download? " ans
case $ans in
   [yY]*) : ;;
   *)     echo "Aborting."; exit 0;;
esac

cd /opt || exit 2

mkdir -p firefox-${version}esr && cd firefox-${version}esr && tar jxvf /tmp/firefox-${version}esr.tar.bz
cd ..
if [ ! -d firefox-${version}esr/firefox ]
then
    echo "No firefox directory in tar file?  Aborting."
    exit 1
fi
echo "Updating symlink"
rm -f firefox
ln -s firefox-${version}esr/firefox firefox

read -p "Delete download? " ans
case $ans in
   [yY]*) rm -f /tmp/firefox-${version}esr.tar.bz ;;
esac

