#! /bin/bash

set -e

cd $(dirname $0)/..
base=$(pwd)

for path in $(find */ \! -name support -type d)
do
        dest=${path/#_/.}
        mkdir -p $HOME/$dest
done

if ln --help | grep -q -e --relative
then
	ln() { command ln -r "$@"; }
fi

if [ support/setcursor.c -nt bin/setcursor ]
then
    cc -Wall support/setcursor.c -o bin/setcursor -lX11
fi

mkdir -p $HOME/lib/X11/fonts $HOME/lib/elisp $HOME/.config/openstack

find . \( \( -name .git -o -name '*.swp' -o -name '*~' -o -name '*#' -o -name support \) -prune \) -o \( -type f -o -type l \) -print |
    cut -c3- |
    while read path
    do
	dest=$HOME/${path/#_/.}
	cmp $path $dest >/dev/null 2>&1 && continue
	case $path in
	    _ssh/*)
		cp -v $path $dest
                if ! ssh -V | grep -q OpenSSH_6
                then
                    sed -e "/#OLD *#/d" -e "s/#OLD //" < $path > $dest
                    sed -e "/#OLD /d" < $path > $dest-old
                fi
		find $HOME/.ssh -perm /077 -print -exec chmod go-rwx {} +
		continue
		;;
	esac
	ln -v -s -f `pwd`/$path $dest
    done

cd ${base}/support
for prof in $HOME/.mozilla/firefox/*/prefs.js
do
    # no use with relative link here, since .mozilla/firefox is not in
    # NFS home.
    command ln -v -s -f `pwd`/firefox/chrome $(dirname "$prof")
done
